version: "3.9"

services:
  load_balancer:
    build: ./load_balancer
    container_name: load_balancer
    ports:
      - "5000:5000"
    networks:
      net1:
        aliases:
          - load_balancer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

  server1:
    build: ./server
    container_name: Server1
    environment:
      - SERVER_ID=1
    networks:
      net1:
        aliases:
          - Server1

  server2:
    build: ./server
    container_name: Server2
    environment:
      - SERVER_ID=2
    networks:
      net1:
        aliases:
          - Server2

  server3:
    build: ./server
    container_name: Server3
    environment:
      - SERVER_ID=3
    networks:
      net1:
        aliases:
          - Server3

networks:
  net1:
    driver: bridge